### ISSUE TITLE
RippleUI breaking tailwindcss default color shades.

### ISSUE THREAD

**Issue by teddbug-S** [Siumauricio/rippleui#39]
**RippleUI breaks tailwindcss colors**
Color shades from tailwindcss changes to very light shades and weired looking colors once
I list rippleui as a required dependency in the tailwind config file.
This gets worse when using the latest version of rippleui.

Occurrs with version 1.4.0

**To Reproduce**
1. `npm install rippleui`
2. Open `tailwindcss.config.js`
3. Add `require("rippleui")` to the plugins list.
4. Restart the tailwindcss build process.

**Expected behavior**
Color shades used before and after the installation of rippleui should be the same
as the original tailwindcss color shades

**Screenshots**
Color shade `bg-green-500` before installing rippleui
![Screenshot from 2023-01-08 06-30-38](https://user-images.githubusercontent.com/68671630/211183632-0a59a966-1c45-409d-8c4e-cfc0beea0b4d.png)

Color shade `bg-green-500` after installing rippleui
![Screenshot from 2023-01-08 06-26-06](https://user-images.githubusercontent.com/68671630/211183594-3a880e05-3dea-4f97-9b80-608af96ef410.png)
![Screenshot from 2023-01-08 06-25-45](https://user-images.githubusercontent.com/68671630/211183596-8b780171-70b3-4480-a731-61e95dcc121f.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu Jammy Jellyfish 22.04 LTS
 - Browser [chromium, brave]

**Smartphone (please complete the following information):**
 - Device: Tecno Spark 2
 - OS: Android 8.0
 - Browser: [ Chrome ]

**Comment by Siumauricio** [comment]
It's working fine, Since RippleUI uses a custom pallete that's why looks different

You can see the pallete here and how to use https://www.ripple-ui.com/docs/get-started/theme

But in the case that you want to use the tailwindcss colors you can use the customization config to override the existing colors

I'll give an example let's suppose you want to change the green-500

in your `tailwind.config.js`

[TailwindCSS pallete](https://tailwindcss.com/docs/customizing-colors)
```diff
/** @type {import('rippleui').Config} */
const config = {
  themes: [
    {
      themeName: "light",
      colors: {
+        "green-500": "#23c55e", // you will override the green-500 in the light theme
      },
    },
  ],
};

/** @type {import('tailwindcss').Config} */
module.exports = {
  // the rest config
  plugins: [
    require("rippleui")({
      ...config,
    })
  ],
};
```

You can read more about customization here https://www.ripple-ui.com/docs/get-started/customization

**Comment by teddbug-S** [comment]
Okay, thanks but I can't just override all the colors I want to use, their quite a lot.

**Comment by tonyalaribe** [comment]
I ran into this issue as well. This makes it difficult to just drop in ripple into an existing app. Could the ripple colors have a different namespace than the tailwind colors? So they can exist side by side. Eg `rpgreen-500` and `rpblue-200`

**Comment by Siumauricio** [comment]
This is something that I have been thinking about, because it will be a breaking change, but eventually I'm gonna be force to do that change since I seen some people don't use the package because it broke the current  Tailwindcss colors.

This weekend I probably release a new version contain this change, I just will think about the semantic name that each color should have.

Thanks for your suggestions!

**Comment by tonyalaribe** [comment]
Yeah. Or atleast provide a way to just disable the colors. 
I tried to disable the dark and light theme following the ripple-ui documentation, but then my [apitoolkit dashboard](https://apitoolkit.io) has no colors anymore. And just looks like some high contrast mode (which actually looks quite nice for a bug tbh), which isn't what I expected by disabling the themes.

<img width="1546" alt="image" src="https://user-images.githubusercontent.com/6564482/222838465-f1dc97e1-45b1-49d6-b2f8-3686af004af4.png">

**Comment by Siumauricio** [comment]
Yes, the reason why the colors looks like with high contrast is because when you remove both themes we are not setting any colors so all the components will loose the reference to the color, but I think the best option and easy is just to rename the colors so we are not going to clash the current colors of tailwind and this going to be more intuitive and doesn't break anything

**Comment by tonyalaribe** [comment]
Thanks @Siumauricio for so quickly making the changes. But I think it's probably not complete.

I noticed a bug where text that should have `color: RGB(255,255,255)` by default are now using CSS variables that don't exist. 
`color: rgb(var(--white) / var(--tw-text-opacity));` where variable `--white` doesn't exist. 

This is only the case with the plugin enabled. otherwise white is a hard coded color and not a CSS variable

**Comment by tonyalaribe** [comment]
I fixed it temporarily by adding 
```
@layer components {
  html {
    --white: 255 255 255;
  }
}
```
to my tailwind css

**Comment by tonyalaribe** [comment]
I also needed to disable the light and dark themes to prevent adding the background colors by default.

**Comment by Siumauricio** [comment]
Thanks for the response @tonyalaribe , I will remove white and black variable from the config

If you want to remove the background and text-color by default you can add a flag to the config `defaultStyle` which is a boolean property

https://www.ripple-ui.com/docs/get-started/customization#how-to-disable-the-background-color-and-color-that-comes-by-default
