### ISSUE TITLE
Improve color documentation

### ISSUE THREAD

**Issue by silveltman** [Siumauricio/rippleui#97]
First of all, very nice components!

However, the theming is a bit confusing to me, especially the colors. The color documentation starts with the nice explanation of the Radix color system; 1 for bg, 2 for subtle bg, 3 for element bg, etc.

However, you don't use this, suddenly the background is net with backgroundPrimary and backgroundSecondary. Text color is set with content-1 till content-3 (using words for bg and numbers for text, a bit confusing imo)

Why is this? Why not have a base-1 till base-12 and automatically apply those to the bg, border, content etc.

What I would suggest as a color scheme:
- base-1 till base-12 which are automatically applied to backgrounds, borders etc
- Allow us to set, for example, primary-1 till primary-12 like this:
```
secondary: {
  1: "...",
  2: "#...",
  3: "#..",
  // ...
}
```
And have that automatically applied when setting btn-primary for example.

If I'm missing something and this does not seem to make sense, please let me know :)

Added: What I also find confusing is that the brand colors, like blue, use a hyphen (red-1) but content does not (content1)

**Comment by Siumauricio** [comment]
Hey @silveltman  Thanks for the interest.

Let me explain this, sometimes you can have different use cases for different components, that's the reasson why we don't follow at 100% same pattern, but they suggest to use the pattern, but I don't agree with that statement because you can have so many scenarios.

I decided to separate the background colors and name as primary and secondary because I consider is more intuitive to the people what they should use instead of having background-1.

About the text colors which is content1, content2 and so on..., I decided to use this scale because sometimes you will have the case when you need to have 3 scales which is with high contrast, medium contrast and low contrast. and the gray 11 and gray 12 from radix-ui i consider is very limited.

Just to put more in context

- For Base Colors we don't use Radix-UI colors which is mainly used in Buttons, Inputs, Links and more components.
- For Content-1, Content-2 and Content-3 we also don't use Radix-UI colors which is used in all the components, But this behavior can be change with customization https://www.ripple-ui.com/docs/get-started/customization#how-to-customize-default-themes
- But the rest of the components like dropdown, sidebar, modal, popover, navbar and more components we use Radix-UI and mainly the gray scale, and a few times the others colors.


As you said there should be more documentation about that colors and summarize all of this to avoid misunderstanding with this section.

Changing the colors structure will be a breaking-change because the people who use this package will need to migrate to the new color structure, one thing that I have been thinking about is to have Components customization just to have more flexibility, For example if we want to modify the colors of Button instead of change the primary color in the whole system, we probably have the case that we want to change only the color of the button and not the rest of the components, we could have something like this:


```js
module.exports = {
	/** @type {import('rippleui').Config} */
	rippleui: {
		themes: [
			{
				themeName: "light",
				colorScheme: "light",
				colors: {
					Button:{
					  // Only a few properties 
					   backgroundColor:"#432443",
					   backgroundHover: "#32345"
					
					}
				},
			},
		],
	},
}
```

This week i will make a update in this section and explain more about these colors.

**Comment by silveltman** [comment]
Thank you @Siumauricio for the explanation, appreciate it! I also think the component specific config could be a cool addition. 

As for changing the color structure, I understand that a breaking change is not what we want here. What would be possible though if that base-1 till base-12 colors are added, and that those are set to gray by default. 

This should make it compatible with the current way of doing things, while still allowing people to change the base neutral colors from gray to olive or sand for example

**Comment by Siumauricio** [comment]
@silveltman  Let me understand this better, So you mean repeat the same scale from `gray` and we will have  both `gray` and `base` ? but what would be the point of add `base` scale?
